# Thông tin dịch vụ
type: object
properties:
  id:
    type: integer
    description: "ID của dịch vụ"
    example: 101
  domain:
    type: string
    description: "Tên miền của dịch vụ"
    example: "example.com"
  type:
    type: string
    description: "Loại dịch vụ"
    example: "Hosting"
