name: Check API Differences

on:
  workflow_call:

jobs:
  diff:
    name: Check API Differences
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with: { path: new }

      - uses: actions/checkout@v4
        with: { ref: main, path: old }

      - name: Install oasdiff
        uses: tufin/oasdiff-action@v1

      - name: Check breaking changes
        id: diff
        run: |
          oasdiff breaking old/openapi.yaml new/openapi.yaml > result.txt 2>&1 || true
          echo "output<<EOF" >> $GITHUB_OUTPUT
          cat result.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          oasdiff breaking old/openapi.yaml new/openapi.yaml --format githubactions -o WARN
